"""empty message

Revision ID: 18954842e2b6
Revises: 52ffe8691233
Create Date: 2019-06-18 11:08:01.813039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18954842e2b6'
down_revision = '52ffe8691233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livestock_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item')
    )
    op.create_table('livestock_breed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('livestock_id', sa.Integer(), nullable=True),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['livestock_id'], ['livestock_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livestock_breed')
    op.drop_table('livestock_items')
    # ### end Alembic commands ###
