"""empty message

Revision ID: 4d95020fad4f
Revises: edc5090f05ae
Create Date: 2019-04-18 18:27:42.090402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d95020fad4f'
down_revision = 'edc5090f05ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produce_items', sa.Column('item', sa.Text(), nullable=True))
    op.drop_column('produce_items', 'newType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produce_items', sa.Column('newType', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('produce_items', 'item')
    # ### end Alembic commands ###
