"""empty message

Revision ID: 52ffe8691233
Revises: cc2febb299c7
Create Date: 2019-06-14 12:37:44.304635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ffe8691233'
down_revision = 'cc2febb299c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
