"""empty message

Revision ID: 707e7fc983e6
Revises: e3418ca8a44f
Create Date: 2019-04-09 17:58:56.354694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707e7fc983e6'
down_revision = 'e3418ca8a44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produce', sa.Column(
        'est_completion_date', sa.Date(), nullable=True))
    op.drop_column('produce', 'date_planted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produce', sa.Column('date_planted',
                                       sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('produce', 'est_completion_date')
    # ### end Alembic commands ###
