"""empty message

Revision ID: c6b3d6713a26
Revises: 4d95020fad4f
Create Date: 2019-04-23 13:07:04.042355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b3d6713a26'
down_revision = '4d95020fad4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livestock', sa.Column('accepted_date', sa.Date(), nullable=True))
    op.add_column('livestock', sa.Column('created_date', sa.Date(), nullable=True))
    op.add_column('livestock', sa.Column('sold_date', sa.Date(), nullable=True))
    op.add_column('produce', sa.Column('accepted_date', sa.Date(), nullable=True))
    op.add_column('produce', sa.Column('certified_organic', sa.Text(), nullable=True))
    op.add_column('produce', sa.Column('created_date', sa.Date(), nullable=True))
    op.add_column('produce', sa.Column('package_size', sa.Integer(), nullable=True))
    op.add_column('produce', sa.Column('package_size_unit', sa.Text(), nullable=True))
    op.add_column('produce', sa.Column('sold_date', sa.Date(), nullable=True))
    op.drop_column('produce', 'gmo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produce', sa.Column('gmo', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('produce', 'sold_date')
    op.drop_column('produce', 'package_size_unit')
    op.drop_column('produce', 'package_size')
    op.drop_column('produce', 'created_date')
    op.drop_column('produce', 'certified_organic')
    op.drop_column('produce', 'accepted_date')
    op.drop_column('livestock', 'sold_date')
    op.drop_column('livestock', 'created_date')
    op.drop_column('livestock', 'accepted_date')
    # ### end Alembic commands ###
