"""empty message

Revision ID: cc2febb299c7
Revises: c6b3d6713a26
Create Date: 2019-05-05 11:58:31.368083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2febb299c7'
down_revision = 'c6b3d6713a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'produce_items', ['item'])
    op.add_column('users', sa.Column('created_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_date')
    op.drop_constraint(None, 'produce_items', type_='unique')
    # ### end Alembic commands ###
