"""empty message

Revision ID: edc5090f05ae
Revises: 707e7fc983e6
Create Date: 2019-04-18 17:30:49.791471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc5090f05ae'
down_revision = '707e7fc983e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produce_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newType', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'farm_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'primary_phone',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'primary_phone',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'farm_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_table('produce_items')
    # ### end Alembic commands ###
